workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      sdk: 34
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
