workflows:
  build_apk:
    name: Build APK
    max_build_duration: 60
    environment:
      flutter: none
      vars:
        ANDROID_KEYSTORE_BASE64: ""
        ANDROID_KEYSTORE_PASSWORD: ""
        ANDROID_KEY_PASSWORD: ""
        ANDROID_KEY_ALIAS: ""
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
